# Generated by Django 4.0.3 on 2022-03-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_c_cpp_java_js_php_py'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
