# Generated by Django 4.0.3 on 2022-04-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='js',
            new_name='CppQuiz',
        ),
        migrations.RenameModel(
            old_name='java',
            new_name='CQuiz',
        ),
        migrations.RenameModel(
            old_name='py',
            new_name='JavaQuiz',
        ),
        migrations.RenameModel(
            old_name='php',
            new_name='JsQuiz',
        ),
        migrations.RenameModel(
            old_name='c',
            new_name='PhpQuiz',
        ),
        migrations.RenameModel(
            old_name='cpp',
            new_name='PythonQuiz',
        ),
    ]
