# Generated by Django 4.0.3 on 2022-04-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_delete_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt1', models.CharField(max_length=120)),
                ('opt2', models.CharField(max_length=120)),
                ('opt3', models.CharField(max_length=120)),
                ('opt4', models.CharField(max_length=120)),
                ('opt5', models.CharField(max_length=120)),
                ('opt6', models.CharField(max_length=120)),
                ('opt7', models.CharField(max_length=120)),
                ('opt8', models.CharField(max_length=120)),
                ('opt9', models.CharField(max_length=120)),
                ('opt10', models.CharField(max_length=120)),
            ],
        ),
    ]
