# Generated by Django 4.0.3 on 2022-04-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_rename_opt1_quiz_ans_remove_quiz_opt10_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
