# Generated by Django 4.0.3 on 2022-04-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='javaquiz',
            name='Option1',
        ),
        migrations.RemoveField(
            model_name='javaquiz',
            name='Option2',
        ),
        migrations.RemoveField(
            model_name='javaquiz',
            name='Option3',
        ),
        migrations.RemoveField(
            model_name='javaquiz',
            name='Option4',
        ),
        migrations.RemoveField(
            model_name='jsquiz',
            name='Option1',
        ),
        migrations.RemoveField(
            model_name='jsquiz',
            name='Option2',
        ),
        migrations.RemoveField(
            model_name='jsquiz',
            name='Option3',
        ),
        migrations.RemoveField(
            model_name='jsquiz',
            name='Option4',
        ),
        migrations.RemoveField(
            model_name='phpquiz',
            name='Option1',
        ),
        migrations.RemoveField(
            model_name='phpquiz',
            name='Option2',
        ),
        migrations.RemoveField(
            model_name='phpquiz',
            name='Option3',
        ),
        migrations.RemoveField(
            model_name='phpquiz',
            name='Option4',
        ),
        migrations.RemoveField(
            model_name='pythonquiz',
            name='Option1',
        ),
        migrations.RemoveField(
            model_name='pythonquiz',
            name='Option2',
        ),
        migrations.RemoveField(
            model_name='pythonquiz',
            name='Option3',
        ),
        migrations.RemoveField(
            model_name='pythonquiz',
            name='Option4',
        ),
    ]
