# Generated by Django 4.0.3 on 2022-04-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Help',
        ),
    ]
